#!/bin/sh
### BEGIN INIT INFO
# Provides:          piupsmonitor
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PiUPS Monitor for CW2. PiUPS+
# Description:       
### END INIT INFO

export PIDFILE="/var/run/piupsmonitor.pid"
 
# Actions
case "$1" in
    start)
        # START
		echo -n "starting piupsmonitor... "
		piupsmonitor > /dev/null 2> /dev/null &
                sleep 2
                if [ -f $PIDFILE ]; then
                        echo "done"
                else
                        echo "failed"
                        tail -1 /var/log/piupsmonitor.log
                fi
        ;;
    stop)
        # STOP
	echo -n "stopping piupsmonitor... "
	if [ "$RUNLEVEL" = "0" ]; then
		piupsmonitor poweroff
	fi
	if [ -f $PIDFILE ]; then
		read ppid < "$PIDFILE"
		kill $ppid
                if [ -f $PIDFILE ]; then
                        echo "failed"
                else
                        echo "done"
                fi

	fi
	;;
    restart)
        # RESTART
	$0 stop
	$0 start
        ;;
    status)
	if [ -f $PIDFILE ]; then
		read ppid < "$PIDFILE"
		if ps --pid $ppid 2>&1 1> /dev/null; then
			echo "$0 is already running as ${ppid}"
		else
			echo "$PIDFILE found, but piupsmonitor is not running"
			rm $PIDFILE
		fi
	else
		echo "$0 is stopped"
	fi
esac
 
exit 0
